version: "3.1"

services:
  frontend:
    container_name: frontend
    build: { context: ./frontend, dockerfile: Dockerfile.dev }

    volumes:
      - ./frontend:/app
      - ./shared:/shared
      - /app/node_modules

    networks:
      - proxy

    depends_on:
      - backend

    restart: always

  backend:
    container_name: backend
    build: { context: ./backend, dockerfile: Dockerfile.dev }

    ports:
      - "5555:5555" # for prisma studio

    volumes:
      - ./backend:/app
      - ./shared:/shared
      - /app/node_modules

    networks:
      - proxy
      - backend

    depends_on:
      - db

    restart: always

  web:
    container_name: web
    image: nginx:alpine

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - proxy

    depends_on:
      - frontend
      - backend

  db:
    container_name: db
    image: postgres:alpine

    volumes:
      - ./db:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    networks:
      - backend

    restart: always

  backup:
    container_name: backup
    build: ./backup

    volumes:
      - ./backup:/backup
      - ./db:/db
      - ./backend/uploads:/uploads

    networks:
      - backend

    restart: always

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.org"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_REPLICATION: "false"

      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d

    ports:
      - "389:389"
      - "636:636"

    domainname: "example.org"
    hostname: "ldap-server"
    
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap

networks:
  proxy:
    driver: bridge
  backend:
    internal: true
