version: "3.1"

services:
  # frontend:
  #   container_name: frontend
  #   build: { context: ./frontend, dockerfile: Dockerfile.dev }

  #   volumes:
  #     - ./frontend:/app

  #   networks:
  #     - proxy

  #   depends_on:
  #     - backend

  #   restart: always

  backend:
    container_name: backend
    build: { context: ./backend, dockerfile: Dockerfile.dev }

    ports:
      - "5555:5555" # for prisma studio

    volumes:
      - ./backend:/app

    networks:
      - proxy
      - backend

    depends_on:
      - db

    restart: always

  # web:
  #   container_name: web
  #   build: ./web

  #   ports:
  #     - "80:80"
  #     - "443:443"

  #   volumes:
  #     - ./web/conf:/etc/nginx/conf.d

  #   networks:
  #     - proxy

  #   depends_on:
  #     - frontend
  #     - backend

  #   restart: always

  db:
    container_name: db
    build: ./db

    volumes:
      - ./db/data:/var/lib/postgresql/data

    networks:
      - backend

    restart: always

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4

  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin

  #   networks:
  #     - proxy
  #     - backend

  #   depends_on:
  #     - db

  #   restart: always

networks:
  proxy:
    driver: bridge
  backend:
    internal: true
