version: "3.1"

services:
  frontend:
    container_name: frontend
    build: ./frontend

    networks:
      - proxy

    depends_on:
      - backend

    restart: always

  backend:
    container_name: backend
    build: ./backend

    volumes:
      - ./backend:/app
      - /app/node_modules

    networks:
      - proxy
      - backend

    depends_on:
      - db

    restart: always

  web:
    container_name: web
    image: nginx:alpine

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - proxy

    depends_on:
      - frontend
      - backend

  db:
    container_name: db
    build: ./db

    volumes:
      - ./db/data:/var/lib/postgresql/data

    networks:
      - backend

    restart: always

networks:
  proxy:
    driver: bridge
  backend:
    internal: true
