FROM oven/bun:debian

WORKDIR /app

COPY package.json ./

RUN bun install

COPY src ./src
COPY prisma ./prisma
COPY tsconfig.json .
COPY .env.development .
COPY startup.dev.sh .
RUN mkdir -p /app/temp

RUN apt-get update && apt-get install -y \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_21.x | bash - &&\
    apt-get install -y nodejs

# Make sure that Windows doesn't mess up the line endings
RUN  apt-get update && apt-get install -y dos2unix && dos2unix ./startup.dev.sh

RUN npm install -g prisma
RUN chmod +x ./startup.dev.sh

CMD ["./startup.dev.sh"]
