FROM oven/bun:debian

COPY . /app/backend
WORKDIR /app/backend

RUN apt-get update && apt-get install -y \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -s https://raw.githubusercontent.com/dkomeza/tiny-git-helper/main/scripts/install.sh | sh
RUN cd /app/backend

CMD ["bun", "dev"]
